### ISSUE TITLE
All Oracle Components Required!!!

### ISSUE THREAD

**Issue by ivanipalacios** [oracle/dino-date#10]
Hi, in order to be able to perform a clean install of Dino-date... we had to install all the components of Oracle (Oracle Text, Spatial, Olap, etc...). As you know, this are components that cause your costs to increase (a lot) as must be licensed... so, we wanted to know if we can install dino-date without having to deploy components that we know that our database is not required to use (Eg. Spatial, etc...).
Thanks.

**Comment by OsBlaineOra** [comment]
There is not currently a version of DinoDate with a reduced feature set.

However, you can install and run it on Oracle XE.  [Here's a link](https://learncodeshare.net/2019/04/22/quick-and-easy-setup-oracle-xe-and-ords-using-docker/) to a blog post on installing Oracle XE in a Docker container.
