### ISSUE TITLE
12g2

### ISSUE THREAD

**Issue by pguerin3** [oracle/dino-date#7]
Can you release DinoDate so it works with 12g2, 18c, and 19c?

**Comment by OsBlaineOra** [comment]
Have you had an issue with any of those Oracle Database releases?

**Comment by stevenfeuerstein** [comment]
Do you mean “Is there a reason to think DD wouldn’t work on them?”

NO

**Comment by pguerin3** [comment]
Yes, I get this error when I run the SQL script to setup the schemas in 12g2:


742     add_member (
743        l_id,
744        'Spinosaurus',
745        'Dot',
746        'dot@example.com',
747           'I like knitting sweaters and booties.  I would have lots of little '
748        || 'tiny dinos with you and knit them all their clothes.  I only knit '
749        || 'with red wool.  I want to meet a creative dinosaur who is good with kids.');
750
751     COMMIT;
752  END;
753  /
                dd_degree_to_sdo ('29-05-37-S', '141-30-31-E'))
                *
ERROR at line 50:
ORA-06550: line 50, column 17:
PL/SQL: ORA-06575: Package or function DD_DEGREE_TO_SDO is in an invalid state
ORA-06550: line 38, column 4:
PL/SQL: SQL Statement ignored
ORA-06550: line 120, column 17:


So when I investigate the function DD.DD_DEGREE_TO_SDO
There is a problem with :

LINE/COL ERROR
-------- -----------------------------------------------------------------
6/13     PL/SQL: Item ignored
6/13     PLS-00201: identifier 'APEX_APPLICATION_GLOBAL.VC_ARR2' must be
         declared




________________________________

**Comment by OsBlaineOra** [comment]
Looks like there's a dependency in there that we don't need.

Thanks for find this, I'll get it taken care of shortly.

**Comment by OsBlaineOra** [comment]
I pushed the change.

@desperate-datesless-din0 could you please try the new version?

Thank you.
